### PR TITLE
Store/retrieve logs from an array instead of system log

### PR DESCRIPTION
**Pull request by inorganik**
I found that using NSLogv and retrieving logs from the system log was unreliable; it omitted many of my logs and included some strange stuff, and didn’t have dates.  (Also I didn’t like the idea of my logs getting
stored in system log). This commit makes the class store logs in a singleton instance of a mutable array instead of the system log, with date/time of log, capped at a certain number of logs. The log can be
saved in applicationWillTerminate: so that it remains continuous through crashes and force quits.

### CODE REVIEW

**Comment by coneybeare** [comment]
This is a breaking change. I would entertain it as a opt-in feature, but not as a rewrite as others may still want the original behavior instead of yours.

**Comment by inorganik** [comment]
Hmm, what if I just renamed `logArrayAsString` as `applicationLog`?

**Comment by coneybeare** [comment]
You need to make it opt-in and backwards compatible, meaning you have to enable a setting to use it like you want to. That way, if we update the repo to include the feature you want, updating for the people who _don't_ want it will not break their already written code. It will work as they expected.

**Comment by inorganik** [comment]
The issue though is that the original feature doesn't really work that well. That's fine you can just deny this request.

**Pull request closed without merging**
